### ISSUE TITLE
Error import with typescript

### ISSUE THREAD

**Issue by Randagio13** [luukdv/hamburger-react#11]
Hi @luukdv,

Thanks for this amazing library!

I have a problem with nextjs and typescript. When I try to import your library, I get an error about module resolution. 

My `tsconfig.json` has `"moduleResolution": "node"` 

Following the error:
`Error: Must use import to load ES Module: `

Could you add this export?

Thanks so much!
Cheers! 🍻

**Comment by luukdv** [comment]
Hey @Randagio13, this has been a long-standing issue over at Next.js: https://github.com/zeit/next.js/issues/706

To solve this, you could create a `next.config.js` and add the following:

```js
module.exports = require('next-transpile-modules')(['hamburger-react'])()`
```

Let me know if this fixes the problem!

**Comment by luukdv** [comment]
Besides the fix above, I'll look into adding a cjs export as a fallback.

**Comment by Randagio13** [comment]
Thanks so much @luukdv !
