### ISSUE TITLE
dist-cjs error in eslint

### ISSUE THREAD

**Issue by sandric** [luukdv/hamburger-react#16]
For some reason my eslint falling with error on file where I import `Hamburger`. Project is on typescript, and everything is working as should actually, so its eslint-only issue. Not sure what causes it, but it fails on simple `eslint --fix <file where you import hamburger>`

![eslint](https://user-images.githubusercontent.com/966443/80111784-ffb01e00-8588-11ea-9f63-deb24a1a154f.png)

**Comment by luukdv** [comment]
I might have a clue about why eslint fails on this one. Will look into it, thanks.

**Comment by sandric** [comment]
Update: if I add `node: true` to eslint `import/resolver` config - no error:

```js
  ...
  settings: {
    "import/resolver": {
      node: true,
      alias: {
        map: [["src", "./src"]],
        extensions: [".ts", ".tsx", ".json"],
      },
    },
  },
  ...
```

**Comment by luukdv** [comment]
@sandric I'm not able to reproduce this yet, could you check if the changes applied in https://github.com/luukdv/hamburger-react/commit/8149bd15dff1c12df1c4f38b3f2890e6393d96a0 would solve this issue?
