### ISSUE TITLE
Feature idea: customize timing function

### ISSUE THREAD

**Issue by cmdalbem** [luukdv/hamburger-react#21]
Hi!

Love the simplicity and elegancy of your component, thanks for sharing it with the world!
I tried to use it on a project of mine, customizing everything I could but it was feeling off, I didn't know why then it hit me. Your component has an opinionated easing function that is very different than what I use on the rest of my website interactions.

Would you mind adding an option to customize this too?

Thanks!

**Comment by luukdv** [comment]
Thanks for the suggestion! I'm gonna add this.

**Comment by luukdv** [comment]
You can now set a custom `transition-timing-function` CSS value, like this:

```jsx
<Hamburger easing="ease-in" />
```

**Comment by cmdalbem** [comment]
omg that was fast!! thanks so much @luukdv ❤️
