### ISSUE TITLE
Ability to add an adjacent label

### ISSUE THREAD

**Issue by jamiewilson** [luukdv/hamburger-react#29]
I was curious if theres a way to add a label next to the icon (e.g. "Menu") that would also toggle the icon animation. Thanks for the help and for publishing this project!

**Comment by luukdv** [comment]
@jamiewilson Sure! An example:

```jsx
const [toggled, toggle] = useState(false)
...
<Hamburger toggle={toggle} toggled={toggled} />
<p onClick={() => toggle(!toggled)}>Open the menu</p>
```

**Comment by jamiewilson** [comment]
Of course! Thank you so much for the help.
