### ISSUE TITLE
Can we change the area size?

### ISSUE THREAD

**Issue by xxidbr9** [luukdv/hamburger-react#38]
I was wonder if we can change the area size,

the default size is 48, and how about if I reduce it using props, let say I change it to 32.

is that possible? thanks

**Comment by luukdv** [comment]
Hi!

The size is adjustable through the `size` prop, but it’s currently not possible to adjust the clickable area to accomodate for https://web.dev/accessible-tap-targets/.

You can always use a negative margin to offset the padding, if it’s causing alignment difficulties.

**Comment by xxidbr9** [comment]
> Hi!
> 
> The size is adjustable through the `size` prop, but it’s currently not possible to adjust the clickable area to accomodate for https://web.dev/accessible-tap-targets/.
> 
> You can always use a negative margin to offset the padding, if it’s causing alignment difficulties.

okay I see, I just wondering that, but after you explain the main reason, thanks.
