### ISSUE TITLE
Can we change Bg color 

### ISSUE THREAD

**Issue by NadirBakhsh** [luukdv/hamburger-react#39]
Hello,
I have a question can we change `backgraound` color on by `condition` use this `toggled` stated

**Comment by luukdv** [comment]
Hey @NadirBakhsh,

Sure! You can do something like this:

<Hamburger color={toggled ? 'pink' : 'purple'}

**Comment by NadirBakhsh** [comment]
No! Color props use for change line color
I want to change background color.

**Comment by luukdv** [comment]
You can change the background color as follows:

```jsx
<div style={{ background: toggled ? 'pink' : 'purple' }}>
  <Hamburger />
</div>
```

**Comment by NadirBakhsh** [comment]
Humburger has default backgroud color.

**Comment by luukdv** [comment]
What do you mean exactly? :) It has a transparent background by default.
