### ISSUE TITLE
Pass click event to toggle and onToggled

### ISSUE THREAD

**Issue by Nicktho** [luukdv/hamburger-react#41]
Hey there, I have a use case to handle the event fired when clicking the underlying dom node that triggers the toggle and onToggled handler. I've created a PR with how this might be implemented.

Let me know what you think! https://github.com/luukdv/hamburger-react/pull/40

**Comment by luukdv** [comment]
Thanks for the suggestion. I've replied here: https://github.com/luukdv/hamburger-react/pull/40#issuecomment-878076635
