### ISSUE TITLE
Disable colour transition

### ISSUE THREAD

**Issue by Nuno111** [luukdv/hamburger-react#42]
Hi there, I am using a dark mode toggle theme, and everything in my website changes colours straight away except the burger menu, is there any way for me to disable transition on colours?

Many thanks

Loving the togglers!

**Comment by luukdv** [comment]
Thanks! 💫

You can disable all the transitions with (`<Hamburger duration={0}`), but at the moment there is no API to do this on a property-basis. The only way would be:

```
.hamburger-react { transition: transform 0.5s }
```

This way, `transform` would still be transitioned, but colors wouldn't be.

**Comment by Nuno111** [comment]
Thank you, will try it out once I figure out how to add custom class to tailwind =P

**Comment by luukdv** [comment]
@Nuno111 An example (`style.css`):

```
@tailwind base;
@tailwind components;
@tailwind utilities;

.hamburger-react {
  transition: transform 1s !important;
}
```

**Comment by Nuno111** [comment]
That's what I did but wasn't working 🤔
