### ISSUE TITLE
Close menu when Link to is clicked. 

### ISSUE THREAD

**Issue by benjaminthedev** [luukdv/hamburger-react#43]
Hi folks, 

This is a great library so thank you! I have a question when a user toggles open the menu and clicks a Link to  - is that a way to have the menu close again. Here is my code: 

<img width="976" alt="Screenshot 2021-08-09 at 13 24 52" src="https://user-images.githubusercontent.com/14097672/128705671-934da828-0a87-4b66-9f71-e017aeb6c356.png">

I have tried to use: 

`toggled={isOpen} toggle={setOpen}`

On the menu anchor tag and list item tag too. What am I doing wrong here?  

Thank you, 

Ben.

**Comment by luukdv** [comment]
Hi! 👋

Thanks. You can do the following:

```jsx
<Link onClick={() => setOpen(false)} to="/">Home</Link>
```
