### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Senninseyi** [luukdv/hamburger-react#45]
I am not sure if its for all but most of the components doesn't have properties for styling `<Sling onToggle={props.clicked}
                   color="white"
                   size={18}
                   hideOutline={true}/>` is there a way to fix this cos i have read the documentations

**Comment by luukdv** [comment]
Hi! There are various props for styling which you can all find on https://hamburger-react.netlify.app, can you clarify what you mean?

**Comment by Senninseyi** [comment]
Okay lemme show an image
![image](https://user-images.githubusercontent.com/25735313/130227802-0092bed0-683b-46f8-9dc4-a2ac90313141.png)

Lets say on mobile version i have this
![image](https://user-images.githubusercontent.com/25735313/130228398-05310404-56e4-4d2b-9a08-d1ed9b244fd6.png)

I want to kind of override the current css that's present in the hamburger

**Comment by luukdv** [comment]
Ah okay, currently that's only possible through css by targeting `.hamburger-react`… Can you indicate what you want to overwrite? That way I know which props are still missing.

By the way, I'm considering adding `style` and `className` props for version `3.0`.

**Comment by Senninseyi** [comment]
Okay thanks a bunch... nice once tho,

**Comment by luukdv** [comment]
By the way, if you could let me know which styles needed overwriting, that would help me determine which props still might be missing. Thanks in advance!

**Comment by rodrigo-arias** [comment]
Hi @luukdv, thank you for your work on this package. I got to this issue looking for some way to add responsive styles. The basic (but not the only thing) is to be able to add a size that is different between resolutions.
I think it would be great if you could add `classNames` so that you have more control over the hamburger. Thanks

**Comment by luukdv** [comment]
Thanks for the clarification @rodrigo-arias 🙂 I'll make sure to add a `className` prop to version `3.0`.

**Comment by riccardolardi** [comment]
@luukdv what happened to the className prop? :) or is this project abandoned?

**Comment by luukdv** [comment]
@riccardolardi As of https://github.com/cyntler/hamburger-react/issues/64, the project is revived. 🙂 Not sure how the [v3 branch](https://github.com/cyntler/hamburger-react/tree/v3) is coming along, that's up to cyntler now.
