### ISSUE TITLE
Add aria-expanded for accessibility

### ISSUE THREAD

**Issue by jgrenat** [luukdv/hamburger-react#46]
Hello! 

To implement the disclosure pattern, that would be nice to be able to add the aria-expanded property.
We can do something similar to https://github.com/luukdv/hamburger-react/pull/15.

I'd be happy to send a PR if you're okay with this feature :)

Thanks!

**Comment by luukdv** [comment]
Thanks for the suggestion!

I'd happily accept a PR. I wouldn't introduce a prop like in https://github.com/luukdv/hamburger-react/pull/15, just setting the value to true/false based on the toggled state.
