### ISSUE TITLE
Doesn't work on mobile view

### ISSUE THREAD

**Issue by binadiegha** [luukdv/hamburger-react#49]
Love this library btw... makes life easy.. but it doesn't seem to work on mobile view and that's where I need it the most

**Comment by luukdv** [comment]
Hi @binadiegha, thanks! Can you provide a link to something like Codepen / Codesandbox with a minimal reproducible example? Without it I can’t help you I'm afraid.

It definitely works on mobile view, see https://hamburger-react.netlify.app on a mobile device as an example.
