### ISSUE TITLE
No animation on mobile

### ISSUE THREAD

**Issue by demjm** [luukdv/hamburger-react#50]
Thanks for the work with this library!

Unfortunately, it seems the animations don't work on mobile, even in the demo site.
There are no transitions, and the menu just go from one form to the other without any animation.
You need to try on a real device, not the devtools

**Comment by luukdv** [comment]
Hi @demjm, I'm not sure why you assume I didn't test this thoroughly on a wide range of devices and browsers. Can you name a specific device (OS version + browser version) you're encountering this on? Then I can look into it.

**Comment by demjm** [comment]
Hey @luukdv 
Sorry if my  comment seemed rough, no offense there.
I’ve tried the burgers on my Iphone X 14.8.1, both on my app and the official website of this package and the examples didn’t work either.

**Comment by luukdv** [comment]
I've tested this again on multiple iPhone X devices, both on 14.x + 15.x and Safari + Chrome. I don't encounter any issues, and haven't had any reports from other users.

Let me know if you have additional details regarding your setup, otherwise closing this.
