### ISSUE TITLE
Change cursor style on icon hover

### ISSUE THREAD

**Issue by daviddwoo** [luukdv/hamburger-react#54]
Hello, thank you for this cool library! 

I am using this for my portfolio site that has a custom cursor pointer. I noticed that there is a cursor with 'pointer' styling when hovered on the menu icons. 

Is there a way to disable the cursor pointer on hover? 

Thanks

**Comment by luukdv** [comment]
Hi! You can change a cursor like this:

```css
.hamburger-react { cursor: … }
```
