### ISSUE TITLE
Animations not working on Chrome iOS

### ISSUE THREAD

**Issue by aer127** [luukdv/hamburger-react#55]
The icon animations are not working on Chrome iOS. Using the demo site (https://hamburger-react.netlify.app/), clicking the icons transitions between states without any animation. Using other browsers on my phone (Safari, Firefox, Edge) the animations work perfectly. Issue seems to be only affecting Chrome. I am running Chrome iOS version 102.0.5005.87 and iOS version 15.5

I've attached videos of the demo site in both Chrome (not-working) and Safari (working)

https://user-images.githubusercontent.com/8918853/172901475-588c5256-fc2e-41be-8a7c-af7e4bd566d4.MP4

https://user-images.githubusercontent.com/8918853/172901471-737ade65-6135-4d17-a390-a85949bbf07d.MP4

**Comment by luukdv** [comment]
Hi! This is a known Chrome iOS issue unfortunately, sometimes CSS transitions stop working (see https://bugs.chromium.org/p/chromium/issues/detail?id=1231712). You can force restart your browser or reboot your device to fix it.
