### ISSUE TITLE
Feature Request: A prop to set width of each lines or different menu style as another component

### ISSUE THREAD

**Issue by milindgoel15** [luukdv/hamburger-react#62]
Basically, i wanted to have my menu in this style:
![image](https://user-images.githubusercontent.com/45682747/228737363-db29b687-2cfe-4963-8f28-5d31e80bcc8d.png)

But the ones i found can either work in only one theme mode or others dont have typescript support(Although having typescript is not much needed but its better that way) and some dont look too good.

Could you add something for this? In the form of line width separately or as a different ham menu style component.\
And also a possibility to reverse the menu.

**Comment by luukdv** [comment]
Hey! Thanks for the feature request.

This does look like a very specific use case though. Adding support for this might only be used by 0.1% of users, while it does increase the bundle size for the other 99.9% of users.

I'll think about it for a little bit, but at the moment it seems like it makes more sense to implement such a custom hamburger yourself.

**Comment by milindgoel15** [comment]
Alright, thanks for your reply.
