### ISSUE TITLE
Looking for new owner 🍔

### ISSUE THREAD

**Issue by luukdv** [luukdv/hamburger-react#64]
I unfortunately don't have the time and/or energy anymore to maintain this library, which means I'm looking for someone who is willing to take over.

It would be amazing if someone is interested to keep giving love to these hamburgers. You'd be making sure this little library (that gets 100K-125K downloads per month) stays alive! Please reach out if that's you or if you know anyone.

**Comment by cyntler** [comment]
@luukdvHi! I really like this library. I even tried to contribute to it regarding to lineWidth, but then I got information from you that v3 is being created, which changes a lot. What do you require from the new owner? If you're thinking of keeping the library up and running as much as possible, then I'm willing! ;)

**Comment by luukdv** [comment]
@cyntler Great to hear that you're interested! I had some plans for v3 indeed, but wasn't able to fully follow through on those. I'll send you a private message to discuss specifics!

**Comment by luukdv** [comment]
@cyntler I was wondering if you found some time to take a look at the e-mail message already? 😊

**Comment by cyntler** [comment]
@luukdv Yes, I see your e-mail. I will response! Sorry for being late! :/ Onboarding to a new company has taken me a lot of time in recent days.
