### ISSUE TITLE
No imperative way to toggle Hamburger

### ISSUE THREAD

**Issue by tonymamo** [luukdv/hamburger-react#7]
Hey there! Saw this package on reddit a few days ago and thought I'd give it a try, I really like the animations.

I tried this out in my project and ran into an issue and wondering if you could help. I have it working to open and close my menu just fine, but inside my menu I want to be able to click on a navigation item and have that close the menu after I click on it. I currently can't fire off a function to affect the Hamburger state, essentially.

What I am proposing is maybe a new property (named `toggled` perhaps?) that accepts a `boolean` value, so that I can control the toggling state of the Hamburger from clicking on something that isn't the Hamburger. 

Example: 
```jsx
// hook for showing/hiding menu
const [menuIsToggled, setMenuIsToggled] = useState(false);

// elsewhere in my code, a function that closes the menu after a navigation item is clicked
const closeMenuAndNavigate = () => {
  // navigate to new page, then close the menu
  navigate('/');
  setMenuIsToggled(false); // close the menu
}

// Later on, I can control the Hamburger's internal state with a `toggled` prop,
// and still use `onToggle` to trigger the change
<Hamburger toggled={menuIsToggled} onToggle={() => setMenuIsToggled(!menuIsToggled)} />
```

Look forward to hearing back. Thanks!

**Comment by luukdv** [comment]
Hey, thanks for opening an issue. I'm currently working on something like this here: https://github.com/luukdv/hamburger-react/commits/custom-state

When finished, you'll be able to provide your own state + setter through a `toggled` and `toggle` prop. In your case, that would look like the following:

```js
const [menuIsToggled, setMenuIsToggled] = useState(false);

const closeMenuAndNavigate = () => {
  navigate('/');
  setMenuIsToggled(false);
}

<Hamburger toggled={menuIsToggled} toggle={setMenuIsToggled} />

```

Let me know if that works for you!

**Comment by tonymamo** [comment]
@luukdv that would work perfectly for me, glad to see you were already working on it! Thanks for the reply, I will keep an eye for that branch to be merged

**Comment by tonymamo** [comment]
🙌  thanks! less than 24 hours turnaround time that's pretty awesome 😄

**Comment by luukdv** [comment]
Hehe. :shipit: No problem!
