### ISSUE TITLE
Please include TypeScript definitions

### ISSUE THREAD

**Issue by SeinopSys** [luukdv/hamburger-react#9]
Thank you for this library! I would love to make use of it in my React project but I use TypeScript and the lack of bindings prevent me from doing so easily. I would appreciate if you published types for your components as well.

**Comment by luukdv** [comment]
Agreed. I don't have a lot of TS experience, but adding a `d.ts` reference should be a good starting point for learning.

**Comment by SeinopSys** [comment]
I can have a go at submitting a PR to move the library into TypeScript if you'd like, only thing you'd need to figure out is how to publish it properly. I know there is some funkyness when publishing TS code to NPM.
